version: '3.7'


volumes:
  node_modules14:
  node_modules15:

services:
  node_15:
    build:
      context: .
      target: NODE_15
    volumes:
      - node_modules15:/app/node_modules/
    # no need to try, those keys are copied Ffrom https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-west-2

  node_14:
    build:
      context: .
      target: NODE_14
    volumes:
      - node_modules14:/app/node_modules/
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-west-2
